[package]
name = "port_and_adapters_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
diesel = { version = "2.1.4", features = ["postgres"] }
rocket = "0.5.0"
rocket_codegen = "0.5.0"

